### ISSUE TITLE
Survival stats HUD

### ISSUE THREAD

**Issue by yooksi** [yoco-labs/odyssey#7] opened 2020-04-24 19:49 UTC
HUD elements to implement:

- [ ] Health bar.
- [ ] Hunger bar.
- [ ] Hydration bar.
- [ ] Stamina bar.
- [ ] Temperature bar.
- [ ] Time cycle box.

- Each combat/survival stat (except day/night cycle) should be represented by an icon with a corresponding gauge indicating the current value.

- The day/night cycle is represented by a graphic placed in the bottom left corner. The needle moves as the cycle progresses with the center being noon and either end being midnight.

![2020-04-24_213547](https://user-images.githubusercontent.com/16436920/80250375-fe0f5480-8673-11ea-8005-a438c79ba1d2.png)

**Comment by yooksi** [comment] 2020-05-04 09:44
I've asked the folks from [project vinum](https://github.com/boredhero/pv) today to help us out by guiding me through the creation of a GUI as they have experience with it.

**Comment by Titus-Armillius** [comment] 2020-05-09 04:40
I'll hopefully be able show you soon my idea for an slightly better representation of the day/night cycle using your graphic as a template.

**Comment by yooksi** [comment] 2020-05-09 05:48
Here is the work in progress banner you are referring to:

![odyssey_time_cycle_banner](https://user-images.githubusercontent.com/16436920/81465291-55abd500-91c9-11ea-9aa2-b55eee003cc6.png)

I will work today to make it wider so there is more empty spaces between sun objects.

**Comment by Titus-Armillius** [comment] 2020-05-09 08:35
Just a preview of the new day/night cycle representation concept.

 I'll go into further detail later; but basically the sun/moon rotate around on a separate layer, the sky moves across the screen on another layer (I realised the arrow should be pointing the other way), and the dunes & border exist on the same layer.

Its hard to represent in word, but on the front layer a duplicate of the sky background moves along simultaneously to shade/highlight the dunes.

I'll explain it better later. 

![](https://i.imgur.com/492Lgl7.png)

**Comment by yooksi** [comment] 2020-05-13 10:58
Your desired concept is a bit too complicated for our initial release, we should stick to the original concept you drafted to keep it simple. The textures need to be scaled to the default Minecraft window size of `427x240` so that I can properly align and position them in the game. Use the following [window template](https://user-images.githubusercontent.com/16436920/81803935-a3517600-9518-11ea-9f11-aefb23ac2f79.png) to scale and position your textures and then export them as individual texture files and provide either the template `xcf` or `png` file with the GUI elements positioned inside so I can see the exact coordinates I have to define in the code.

So just to be clear I require the following things:

- Exact coordinates of each GUI element in a default sized (`427x240`) window layout.
- Texture files that were scaled to the default window size.
- Either the Gimp project file or exported `png` of the GUI layout so I know were to position the elements on the screen, because I have to define these coordinates in the code.

**Comment by Titus-Armillius** [comment] 2020-05-14 01:06
Here is a link to the xcf file, image with elements included, and all the textures: https://mega.nz/folder/AC40XQrJ#Z7_t3Ho7uAUdx0de3bU8Bw

I noticed that the coordinate numbers in gimp are top down, so I didn't include them in case you need the opposite.

The coordinates can be found by selecting each element and hovering over the corners/ends.

Hope this works well :)

**Closed** 2020-06-02 01:07 UTC
Labels: feature, gui
